server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    hostname: localhost
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true

          #cambiar ojjo
      routes:
        - id: nrs-libro-service
          uri: lb://nrs-libro-service
          predicates:
            - Path=/libros/**


        - id: ms-kajita-service
          uri: lb://ms-kajita-service
          predicates:
            - Path=/productos/**

        - id: ms-test01post-service
          uri: lb://ms-test01post-service
          predicates:
            - Path=/ventas/**

        - id: ms-cliente-service-route
          uri: lb://ms-cliente-service
          predicates:
            - Path=/clientes/**
