server:
  port: 8082

spring:
  application:
    name: nrs-usuario-service # Mantenemos el nombre del servicio

  datasource:
    url: jdbc:postgresql://localhost:5432/nrs_usuario
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


  h2:
    console:
      enabled: false # Deshabilitamos la consola de H2



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30