server:
  port: 8081


spring:
  application:
    name: nrs-libro-service

  datasource:
    url: jdbc:mysql://localhost:3306/nrs_libro
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  #datasource:
  #  url: jdbc:h2:mem:ms_catalogo
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #  password: password

  #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90